# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdef3c8e2ab87d3c38781999e66c3df1a7050acb86c3794e9a41e6d82f7b601660331dd7aa52f57f23b4b3ae7ad42e0a124ae82fe1874e70202a9cf64154923f

test:
  secret_key_base: d4fb5c71449f922989a805ec49207f55fe9083142f273a01f0ca51327c25eaafbf02da5989b092c8d7eca74bd605dff714b034f8abcb4d23bf43060656e4e5fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
